// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa2wEhT-L557ZUMSu7wjmC40KosTAE-90',
    appId: '1:316175442868:web:76027d62830561150a48e1',
    messagingSenderId: '316175442868',
    projectId: 'inclass14-fcm',
    authDomain: 'inclass14-fcm.firebaseapp.com',
    storageBucket: 'inclass14-fcm.firebasestorage.app',
    measurementId: 'G-4PJ5HLMFTE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5d-mJbRj2a2ZAX-eiUKqhG5srbo9RjnI',
    appId: '1:316175442868:android:69ee3dfeccb6ea270a48e1',
    messagingSenderId: '316175442868',
    projectId: 'inclass14-fcm',
    storageBucket: 'inclass14-fcm.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAa2wEhT-L557ZUMSu7wjmC40KosTAE-90',
    appId: '1:316175442868:web:6bcf2454d6bf45430a48e1',
    messagingSenderId: '316175442868',
    projectId: 'inclass14-fcm',
    authDomain: 'inclass14-fcm.firebaseapp.com',
    storageBucket: 'inclass14-fcm.firebasestorage.app',
    measurementId: 'G-57BKLPHZWD',
  );
}
